### ISSUE TITLE
Need email server

### ISSUE THREAD

**Issue by kyyberi** [educloudalliance/educloud-consortium#6]
We need to have email server since we need email address that use educloudalliance domain. Kolab perhaps?

**Comment by kyyberi** [comment]
Upcloud sponsors some server time for us (enough) to start running email services on their cloud instead of JulkICT lab. We have to leave lab this year anyway and thus this move makes sense. Thanks to UpCloud! Details will be recorded to wiki and portal.

**Comment by preriasusi** [comment]
https://mail.educloudalliance.org is now powered by Mail-in-a-box in UpCloud. First mails sent.

**Comment by kyyberi** [comment]
solved
